[fix gate] Use upper-constraints on image build
Currently building an image uses requirements but not upper-constraints.
This can cause an issue when libraries change and the image becomes out
of sync with the server code (for example when oslo.context changes).

Trove integration now uses upper-constraints as well when building
images.

Change-Id: Iba5e9976ff9522b7b6fdd523ed78fc6d9b70ea6c
Closes-Bug: #1603506

diff --git a/scripts/files/elements/ubuntu-guest/extra-data.d/15-reddwarf-dep b/scripts/files/elements/ubuntu-guest/extra-data.d/15-reddwarf-dep
--- a/scripts/files/elements/ubuntu-guest/extra-data.d/15-reddwarf-dep
+++ b/scripts/files/elements/ubuntu-guest/extra-data.d/15-reddwarf-dep
@@ -8,6 +8,7 @@ set -o xtrace
 
 source $_LIB/die
 
+UC_BRANCH=${BRANCH_OVERRIDE:-master}
 BRANCH_OVERRIDE=${BRANCH_OVERRIDE:-default}
 ADD_BRANCH=$(basename ${BRANCH_OVERRIDE})
 REQUIREMENTS_FILE=${REDSTACK_SCRIPTS}/files/requirements/ubuntu-requirements-${ADD_BRANCH}.txt
@@ -17,3 +18,12 @@ REQUIREMENTS_FILE=${REDSTACK_SCRIPTS}/files/requirements/ubuntu-requirements-${A
 [ -n "$HOST_USERNAME" ] || die "HOST_USERNAME not set"
 
 sudo -Hiu ${HOST_USERNAME} dd if=${REQUIREMENTS_FILE} of=${TMP_HOOKS_PATH}/requirements.txt
+
+# Grab the upper constraints file, but don't fail if we can't find it
+DIR=$(pwd)
+UPPER_CONSTRAINTS_FILE=upper-constraints.txt
+set +e; curl -o ${DIR}/${UPPER_CONSTRAINTS_FILE} https://git.openstack.org/cgit/openstack/requirements/plain/${UPPER_CONSTRAINTS_FILE}?h=${UC_BRANCH}; set -e
+if [ -f "${DIR}/${UPPER_CONSTRAINTS_FILE}" ]; then
+    sudo -Hiu ${HOST_USERNAME} dd if=${DIR}/${UPPER_CONSTRAINTS_FILE} of=${TMP_HOOKS_PATH}/${UPPER_CONSTRAINTS_FILE}
+    rm -f ${DIR}/${UPPER_CONSTRAINTS_FILE}
+fi
