Updated ubuntu-db2 to use datastore-package element to copy files
This element
1. provides a common place to copy packages into the image
   for installing them during image building. So now every
   image element doesn't need to provide extra-data and
   install scripts to do the same work
2. provides user ability to specify the location of the package
   as file/directory/url

Change-Id: Ie15079f5eb0b9bed3f343c78357772f7a2d21ea8

diff --git a/scripts/files/elements/ubuntu-db2/install.d/10-db2 b/scripts/files/elements/ubuntu-db2/install.d/10-db2
--- a/scripts/files/elements/ubuntu-db2/install.d/10-db2
+++ b/scripts/files/elements/ubuntu-db2/install.d/10-db2
@@ -12,7 +12,17 @@ DB2_PKG_LOCATION="/db2"
 mkdir ${DB2_PKG_LOCATION}
 cd ${DB2_PKG_LOCATION}
 
-tar -xvzf /tmp/in_target.d/db2.tar.gz
+if [ -f /opt/datastore_package/db2.tar.gz ]
+then
+    tar -xvzf /opt/datastore_package/db2.tar.gz
+elif [ -f /opt/datastore_package/v10.5_linuxx64_expc.tar.gz ]
+then
+    tar -xvzf /opt/datastore_package/v10.5_linuxx64_expc.tar.gz
+else
+    echo "ERROR: DB2 Package (db2.tar.gz or v10.5_linuxx64_expc.tar.gz) not found in /opt/datastore_package/"
+    echo "Please register and download the DB2 Express-C packages to a private repository or local filesystem."
+    exit 1
+fi
 
 # installing dependencies
 apt-get install libaio1
