Allow specifying project branch in redstack
At present, redstack clones the most recent version of devstack and
each project.  Sometimes this is undesirable as these repositories can
become unstable.  A solution to this would be to add an environment
variable or option to redstack to specify the branch or commit to use
(with the default remaining 'master').

With this change you can now specify scenarios like:

- To switch all projects (including devstack) to a stable branch:
PROJECT_BRANCH=stable/kilo ./redstack install

- To switch all projects to a stable branch, but have a specific
  devstack commit used:
PROJECT_BRANCH=stable/kilo DEVSTACK_BRANCH=7ef2464 ./redstack install

- To switch all projects (including devstack) to a stable branch,
but have a specific commit for Nova:
PROJECT_BRANCH=stable/kilo NOVA_BRANCH=7ef2464 ./redstack install

- To switch all projects to a stable branch, but have a different
stable branch for the clients:
PROJECT_BRANCH=stable/juno PROJECT_CLIENT_BRANCH=stable/kilo ...

Redstack would then switch to the corresponding branches/commits
before running './stack.sh'

Optionally, for persistence, these variables can be defined in either
options.rc or ~/.redstack.options.rc

The repos are switched, even if the project directories already existed.

If an invalid branch/commit is specified, redstack stops with an error
message.

The following environment variables are now supported (in order of
precedence):
<PROJECT>_BRANCH - where <PROJECT> is either DEVSTACK or is defined
                   in *projects-list
                   i.e. NOVA_BRANCH, CINDER_BRANCH, DEVSTACK_BRANCH
PROJECT_CLIENT_BRANCH
PROJECT_BRANCH

Note: Setting PROJECT_BRANCH or PROJECT_CLIENT_BRANCH will *not*
affect the Trove project - you must use TROVE_BRANCH and
PYTHON_TROVECLIENT specifically for that.

Change-Id: I50c64db917bb87bac5d1b1d4d0231270577e26a8
Closes-Bug: #1449627

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -271,3 +271,44 @@ function get_bool() {
 
     echo $VALUE
 }
+
+# Get the project branch to switch to.  Uses PROJECT_BRANCH_NAME,
+# then BRANCH_DEFAULT, then 'master'
+function get_project_branch() {
+    local PROJECT_BRANCH_NAME=$1
+    local BRANCH_DEFAULT=${2:-master}
+
+    PROJECT_BRANCH_OVERRIDE=${!PROJECT_BRANCH_NAME}
+
+    BRANCH=${PROJECT_BRANCH_OVERRIDE:-$BRANCH_DEFAULT}
+
+    echo "$BRANCH"
+}
+
+# Try to switch to a branch or commit in a repo
+# Fails if the branch/commit doesn't exist
+function git_checkout() {
+    local PROJECT=$1
+    local REPO_DIR=$2
+    local REPO_BRANCH=$3
+    local REPO_BRANCH_VAR_NAME=$4
+
+    if [ -n "$REPO_BRANCH" ]; then
+        pushd "$REPO_DIR"
+        if [ $PROJECT == "diskimage-builder" ] || [ $PROJECT == "tripleo-image-elements" ]; then
+            REPO_BRANCH=master
+        fi
+        GIT_STATUS=$(git checkout "$REPO_BRANCH" &> /dev/null || echo "failed")
+        if [[ "$GIT_STATUS" = "failed" ]]; then
+            exclaim "${COLOR_RED}Could not switch to branch/commit '$REPO_BRANCH' in $PROJECT, exiting${COLOR_NONE}"
+            echo "Please set '$REPO_BRANCH_VAR_NAME' to a valid branch/commit and try again."
+            echo "Note: This error may also mean that there are modified files in $PROJECT."
+            echo "      If that is the case, please stash them and re-run your command."
+            exit 1
+        else
+            exclaim "${COLOR_BLUE}Using $PROJECT branch '$REPO_BRANCH'${COLOR_NONE}"
+        fi
+        popd
+    fi
+}
+
