Don't reset HOME in redstack
Currently redstack resets HOME as the first thing that it does. It
isn't particlularly apparent why this is required; it may have been
needed in a long ago time when paths to thing were
trove-integrations/scripts relative but they aren't now.

I've left the code in for now, with a #TODO just in case someone has
scripts that leverage or extend redstack and they want the old
behavior. I'll delete this code later. Hence this change has
Partial-Bug and not Closes-Bug.

Change-Id: If0f7329ea37f6d92f10b815c7a96eaee97d8b6d4
Partial-Bug: #1552048

diff --git a/scripts/redstack b/scripts/redstack
--- a/scripts/redstack
+++ b/scripts/redstack
@@ -173,17 +173,24 @@ function pkg_update () {
 }
 
 function set_home_dir() {
-    self="${0#./}"
-    base="${self%/*}"
-    current=`pwd`
-    if [ "$base" = "$self" ] ; then
-        HOME="$current/"
-    elif [[ $base =~ ^/ ]]; then
-        HOME="$base/"
-    else
-        HOME="$current/$base/"
-    fi
+    exclaim "set_home_dir has been nooped."
+    exit 1
 }
+
+# This is the old set_home_dir function that is being nooped in bug 1552048.
+# TODO (amrith) delete this code and cleanup.
+# function set_home_dir() {
+#     self="${0#./}"
+#     base="${self%/*}"
+#     current=`pwd`
+#     if [ "$base" = "$self" ] ; then
+#         HOME="$current/"
+#     elif [[ $base =~ ^/ ]]; then
+#         HOME="$base/"
+#     else
+#         HOME="$current/$base/"
+#     fi
+# }
 
 function set_http_proxy() {
     if [ ! "${http_proxy}" = '' ]; then
@@ -1240,7 +1247,7 @@ fi
 # Set this to exit immediately on error
 set -o errexit
 
-set_home_dir
+# set_home_dir
 set_http_proxy
 set_trove_plugin_vars false
 
