Change DATASTORE_PKG_LOCATION for vertica
Vertica Management console requires additional
debian packages to be installed as well as other
files for the management console to run

DATASTORE_PKG_LOCATION is a directory that has
all files that need to be installed on the image

Additional changes are made to some global variables
to make sure the environment can run the
management console.

Closes-Bug: #1452926

Change-Id: I2863a21d186d9c809fa2fdb0050e4728e100b010

diff --git a/scripts/files/elements/ubuntu-vertica/extra-data.d/93-copy-vertica-deb b/scripts/files/elements/ubuntu-vertica/extra-data.d/93-copy-vertica-deb
--- a/scripts/files/elements/ubuntu-vertica/extra-data.d/93-copy-vertica-deb
+++ b/scripts/files/elements/ubuntu-vertica/extra-data.d/93-copy-vertica-deb
@@ -10,5 +10,20 @@ set -o xtrace
 source $_LIB/die
 
 [ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"
-[ -f "$DATASTORE_PKG_LOCATION" ] || die "Datastore package installer file not found at:" $DATASTORE_PKG_LOCATION
-dd if=${DATASTORE_PKG_LOCATION} of=${TMP_HOOKS_PATH}/vertica.deb
+[ -d "$DATASTORE_PKG_LOCATION" ] || die "Datastore package installer files not found at the directory:" $DATASTORE_PKG_LOCATION
+
+mkdir $TMP_HOOKS_PATH/vertica
+
+cd $DATASTORE_PKG_LOCATION
+# remove the version number form the debian package name before copying
+for vertica_file in `ls -1 $DATASTORE_PKG_LOCATION`
+do
+    if [[ $vertica_file == *".deb" ]]
+    then
+        package_name=$(basename "$vertica_file" ".deb")
+        deb_file_name=`echo $package_name | cut -d "_" -f 1`
+        cp $vertica_file $TMP_HOOKS_PATH/vertica/$deb_file_name.deb
+    else
+        cp $vertica_file $TMP_HOOKS_PATH/vertica/$vertica_file
+    fi
+done
